---
detectors:
  Attribute:
    enabled: false
  ControlParameter:
    enabled: false
  DuplicateMethodCall:
    enabled: false
  InstanceVariableAssumption:
    enabled: false
  IrresponsibleModule:
    enabled: false
  NestedIterators:
    enabled: false
  NilCheck:
    enabled: false
  RepeatedConditional:
    enabled: false
  TooManyStatements:
    enabled: false
  UncommunicativeVariableName:
    enabled: false
  UtilityFunction:
    enabled: false
