AllCops:
  DisplayCopNames: true
  DisplayStyleGuide: true
  TargetRubyVersion: 2.5
  Exclude:
    - 'spec/**/**/*'
LineLength:
  Max: 100
Layout/EmptyLinesAroundClassBody:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Style/Dir:
  Enabled: false
Style/Documentation:
  Enabled: false
Style/ExpandPathArguments:
  Enabled: false
