sudo: false
language: ruby
rvm:
  - ruby-head
before_install:
  - sudo apt-get install libxml2-dev
  - gem update --system
  - gem install bundler
  - bundle install
script:
  - bundle exec rake
notifications:
  disable: true
